name: Build Windows Library via Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-windows:
    name: Build Windows Library
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Make script executable
      run: chmod +x travis/build-docker-win.sh
      
    - name: Run build script
      run: ./travis/build-docker-win.sh
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-output
        path: |
          build/
          output/
          libvosk.lib
        retention-days: 30
