name: Build Windows Library via Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1

jobs:
  build-windows:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Make script executable
      run: chmod +x travis/build-docker-win.sh

    - name: Run build script with cache
      run: |
        # Set Docker buildkit and cache options
        export DOCKER_BUILDKIT=1
        export BUILDKIT_INLINE_CACHE=1
        ./travis/build-docker-win.sh
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
